In [ ]:
# used doi_10_5061_dryad_zgmsbccjk__v20241112.zip
# obtained from https://datadryad.org/dataset/doi:10.5061/dryad.zgmsbccjk
# stored under data dir within same directory as this file.

import duckdb


with duckdb.connect() as conn:
    df_disambiguation = conn.execute(
        """
        WITH disambig_software AS (
            SELECT DISTINCT 
                software
            FROM "doi_10_5061_dryad_zgmsbccjk__v20241112/mentions/disambiguation_files/final_output/*.csv.gz"
        )
        SELECT
            ID,
            software_mention,
            mapped_to,
            source,
            platform,
            package_url,
            description,
            homepage_url,
            license,
            github_repo
        FROM "doi_10_5061_dryad_zgmsbccjk__v20241112/mentions/linked/metadata.tsv.gz"
        WHERE 
            software_mention IN (SELECT software FROM disambig_software)
            AND github_repo IS NOT NULL
            AND github_repo <> ''
            AND exact_match = True
    """
    ).df()
df_disambiguation

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/zw/l3g4vq6508g98qkt05z6hb_m0000gp/T/ipykernel_49194/3224199319.py", line 4, in <module>
    with duckdb.connect() as conn:
         ~~~~~~~~~~~~~~^^
  File "/var/folders/zw/l3g4vq6508g98qkt05z6hb_m0000gp/T/ipykernel_49194/3224199319.py", line 5, in <module>
    df_disambiguation = conn.execute(
                        ~~~~~~~~~~~~^
        """
        ^^^
    ...<22 lines>...
    """
    ^^^
    ).df()
    ^
_duckdb.IOException: IO Error: No files found that match the pattern "doi_10_5061_dryad_zgmsbccjk__v20241112/mentions/linked/metadata.tsv.gz"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
        etype, value, tb, tb_offset=tb_offset
    )
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, etype, evalue, etb, tb_offset, number_of_lines_of_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, etype, value, tb, tb_offset, number_of_lines_of_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                                                           tb_offset)
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1063, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/IPython/core/ultratb.py", line 1160, in get_records
    res = list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
          ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/stack_data/core.py", line 597, in stack_data
    yield from collapse_repeated(
    ...<4 lines>...
    )
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/stack_data/utils.py", line 83, in collapse_repeated
    yield from map(mapper, original_group)
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/stack_data/core.py", line 587, in mapper
    return cls(f, options)
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/stack_data/core.py", line 551, in __init__
    self.executing = Source.executing(frame_or_tb)
                     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/executing/executing.py", line 283, in executing
    assert_(new_stmts <= stmts)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/buntend/Documents/work/almanac/.venv/lib/python3.13/site-packages/executing/executing.py", line 80, in assert_
    raise AssertionError(str(message))
AssertionError

In [ ]:
df_disambiguation.dropna(subset=["github_repo"]).to_parquet("czi_disambiguated_biomedical_software_github_refs.parquet", index=False)

,ID,software_mention,mapped_to,source,platform,package_url,description,homepage_url,other_urls,license,github_repo,github_repo_license,exact_match,RRID,reference,scicrunch_synonyms
0,SM1940656,csp,CSP,Github API,NaN,https://github.com/carlwoodfin/CSP,This is a simple RSS for Coolsmartphone.com. H...,[],[],NaN,https://github.com/carlwoodfin/CSP,None,True,NaN,NaN,[]
1,SM1796382,algorithm,algorithm,Github API,NaN,https://github.com/hextriclosan/algorithm,Collection of Algorithms,[],[],NaN,https://github.com/hextriclosan/algorithm,None,True,NaN,NaN,[]
2,SM1796382,algorithm,algorithm,Github API,NaN,https://github.com/gardnerss/algorithm,알고리즘 스터디,[],[],NaN,https://github.com/gardnerss/algorithm,None,True,NaN,NaN,[]
3,SM1796382,algorithm,algorithm,Github API,NaN,https://github.com/masshun/algorithm,NaN,[],[],NaN,https://github.com/masshun/algorithm,None,True,NaN,NaN,[]
4,SM1826612,vscode,vscode,Github API,NaN,https://github.com/HARSHADEVICE/vscode,NaN,[],[],NaN,https://github.com/HARSHADEVICE/vscode,None,True,NaN,NaN,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424138,SM1930857,spc,spc,Github API,NaN,https://github.com/ssddanbrown/spc,Simple Page Checker,[],[],NaN,https://github.com/ssddanbrown/spc,None,True,NaN,NaN,[]
424139,SM2820905,qpsolvers,QPSolvers,Github API,NaN,https://github.com/detu/QPSolvers,Implementation of some QP solvers.,[],[],NaN,https://github.com/detu/QPSolvers,None,True,NaN,NaN,[]
424140,SM2013575,static,static,Github API,NaN,https://github.com/roberth-adalid/static,NaN,[],[],NaN,https://github.com/roberth-adalid/static,None,True,NaN,NaN,[]
424141,SM2013575,static,static,Github API,NaN,https://github.com/teamplanes/static,A zero config CLI tool for deploying static si...,[],[],NaN,https://github.com/teamplanes/static,None,True,NaN,NaN,[]
424142,SM2049429,pyitlib,pyitlib,Github API,NaN,https://github.com/pafoster/pyitlib,A library of information-theoretic methods imp...,[],[],NaN,https://github.com/pafoster/pyitlib,None,True,NaN,NaN,[]

In [ ]:
df_disambiguation["software"]

0                                                    RAKF
1          Arduino Integrated Development Environment IDE
2                                        GalleyStatus XML
3                                                GelQuest
4                                                Y Win 32
                                ...
2106681                                   MEME Suite Tool
2106682                                    SCOP interface
2106683                                         ChibiRobo
2106684                                   Devices MetaVue
2106685                                  AGENT CUSTOMIZER
Name: software, Length: 2106686, dtype: str

In [13]:
import duckdb


with duckdb.connect() as conn:
    df_disambiguation = conn.execute("""
        SELECT *
        FROM "disambiguation/*.csv.gz"
        LIMIT 1
    """).df()
df_disambiguation

,sentence_id,doi,pmc_id,sentence,source,software,mention_id,disambiguated_software
0,326417514543,10.1111/pai.13824,PMC9349415,2.6 Systems serology analysis To holistically ...,europe_pmc,MATLAB,SM3160092,matlab

In [7]:
import pandas as pd
df_meta = pd.read_csv("metadata.tsv.gz", sep="\t", compression="gzip")

df_meta.info()

/var/folders/zw/l3g4vq6508g98qkt05z6hb_m0000gp/T/ipykernel_4185/2167046002.py:2: DtypeWarning: Columns (0: platform, 1: license, 2: RRID, 3: reference) have mixed types. Specify dtype option on import or set low_memory=False.
  df_meta = pd.read_csv("metadata.tsv.gz", sep="\t", compression="gzip")

<class 'pandas.DataFrame'>
RangeIndex: 768566 entries, 0 to 768565
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   768566 non-null  str
 1   software_mention     768528 non-null  str
 2   mapped_to            768524 non-null  str
 3   source               768566 non-null  str
 4   platform             60388 non-null   str
 5   package_url          768566 non-null  str
 6   description          422785 non-null  str
 7   homepage_url         768566 non-null  str
 8   other_urls           768566 non-null  str
 9   license              45821 non-null   str
 10  github_repo          730378 non-null  str
 11  github_repo_license  0 non-null       float64
 12  exact_match          768566 non-null  bool
 13  RRID                 11069 non-null   str
 14  reference            12973 non-null   str
 15  scicrunch_synonyms   768566 non-null  str
dtypes: bool(1), float64(1), str(14)
memory usage: 88.7 MB

In [9]:
df_meta.head()

,ID,software_mention,mapped_to,source,platform,package_url,description,homepage_url,other_urls,license,github_repo,github_repo_license,exact_match,RRID,reference,scicrunch_synonyms
0,SM1790660,grridge,GRridge,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Better prediction by use of co-data: Adaptive ...,[],[],GPL-3,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.GRridge,[]
1,SM1871781,compass,COMPASS,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Combinatorial Polyfunctionality Analysis of Si...,[],[],Artistic-2.0,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.COMPASS,[]
2,SM1947519,hilda,HiLDA,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Conducting statistical inference on comparing ...,[],[],GPL-3,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.HiLDA,[]
3,SM1987983,anf,ANF,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Affinity Network Fusion for Complex Patient Cl...,[],[],GPL-3,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.ANF,[]
4,SM1993089,ringo,Ringo,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,R Investigation of ChIP-chip Oligoarrays,[],[],Artistic-2.0,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.Ringo,[]

In [20]:
df_meta[df_meta["software_mention"].isin(df_disambiguation["software"])].drop_duplicates(subset=["mapped_to"])

,ID,software_mention,mapped_to,source,platform,package_url,description,homepage_url,other_urls,license,github_repo,github_repo_license,exact_match,RRID,reference,scicrunch_synonyms
0,SM1790660,grridge,GRridge,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Better prediction by use of co-data: Adaptive ...,[],[],GPL-3,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.GRridge,[]
1,SM1871781,compass,COMPASS,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Combinatorial Polyfunctionality Analysis of Si...,[],[],Artistic-2.0,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.COMPASS,[]
5,SM2023831,tronco,TRONCO,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,"TRONCO, an R package for TRanslational ONCOlogy",[],[],GPL-3,NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.TRONCO,[]
6,SM2133679,affxparser,affxparser,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Affymetrix File Parsing SDK,[],[],LGPL (>= 2),NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.affxparser,[]
8,SM3121094,flowsom,FlowSOM,Bioconductor Index,Bioconductor,https://www.bioconductor.org/packages/release/...,Using self-organizing maps for visualization a...,[],[],GPL (>= 2),NaN,NaN,True,NaN,https://doi.org/doi:10.18129/B9.bioc.FlowSOM,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768293,SM2447370,uest,uest,Github API,NaN,https://github.com/abernier/uest,NaN,[],[],NaN,https://github.com/abernier/uest,NaN,True,NaN,NaN,[]
768418,SM2186732,rqpen,rqpen,Github API,NaN,https://github.com/bssherwood/rqpen,Penalized Quantile Regression,[],[],NaN,https://github.com/bssherwood/rqpen,NaN,True,NaN,NaN,[]
768426,SM2374191,oref0,oref0,Github API,NaN,https://github.com/openaps/oref0,oref0: The open reference implementation of th...,[],[],NaN,https://github.com/openaps/oref0,NaN,True,NaN,NaN,[]
768485,SM3123277,gama,GAMA,Github API,NaN,https://github.com/gabrielhdt/GAMA,Vectorisation d'images,[],[],NaN,https://github.com/gabrielhdt/GAMA,NaN,True,NaN,NaN,[]
768487,SM1843777,egsa,EGSA,Github API,NaN,https://github.com/MahmoudMohamed99/EGSA,For Tranning,[],[],NaN,https://github.com/MahmoudMohamed99/EGSA,NaN,True,NaN,NaN,[]

In [10]:
df_meta.tail()

,ID,software_mention,mapped_to,source,platform,package_url,description,homepage_url,other_urls,license,github_repo,github_repo_license,exact_match,RRID,reference,scicrunch_synonyms
768561,SM2008052,pump,Pump,Github API,NaN,https://github.com/huxq17/Pump,NaN,[],[],NaN,https://github.com/huxq17/Pump,NaN,True,NaN,NaN,[]
768562,SM2007730,planck,Planck,Github API,NaN,https://github.com/pankleks/Planck,NaN,[],[],NaN,https://github.com/pankleks/Planck,NaN,True,NaN,NaN,[]
768563,SM3129989,application,application,Github API,NaN,https://github.com/RainySeason/application,软件,[],[],NaN,https://github.com/RainySeason/application,NaN,True,NaN,NaN,[]
768564,SM3129989,application,application,Github API,NaN,https://github.com/qcubed/application,"v4 Application repository, containing the form...",[],[],NaN,https://github.com/qcubed/application,NaN,True,NaN,NaN,[]
768565,SM3337180,pwnd,Pwnd,Github API,NaN,https://github.com/Fargekritt/Pwnd,Check if password is leaked with pwnedpassword...,[],[],NaN,https://github.com/Fargekritt/Pwnd,NaN,True,NaN,NaN,[]